---
language: java
before_install:
- unset SORCER_HOME
- export SORCER_HOME=`pwd`
- unset RIO_HOME
- export RIO_HOME=$SORCER_HOME/target/rio
- echo "SORCER_HOME is $SORCER_HOME"
- echo "RIO_HOME is $RIO_HOME"
install: mvn -q -P disttest install
before_script:
- cd distribution/target/sorcer-*/sorcer-*/
- export SORCER_HOME=`pwd`
- unset RIO_HOME
- "$SORCER_HOME/bin/sorcer-boot &"
- sleep 12
script: cd $SORCER_HOME/../../../../tests/ && mvn -Dmaven.test.skip=false test
jdk:
- oraclejdk7
